services:
  - type: web
    name: ats-backend
    env: docker
    dockerContext: AtsApi
    dockerfilePath: AtsApi/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Data Source=/app/ats.db"
